theme: jekyll-theme-minimal
title: Welcome to my portfolio!
description: Here I share samples of my work reflecting my varried experiences and interests, from operational reserach modelling to embedded systems, from social enterprise to the arts.  
